homeassistant:
  customize:
    sensor.disk_used_:
      friendly_name: Rpi Disk Used
    sensor.uptime:
      friendly_name: 'Rpi Hass Uptime'

group:
  system_monitor_card:
    name: System Monitor Hass Rpi
    entities:
      - alert.disk_use_critical
      - sensor.uptime
      - sensor.last_boot
      - sensor.disk_used__2
      - sensor.disk_used_
      - sensor.since_last_boot

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: memory_free
      - type: last_boot
      - type: since_last_boot

  - platform: uptime
    unit_of_measurement: hours

binary_sensor:
  - platform: template
    sensors:
      critical_disk_use:
        value_template: '{{ states.sensor.disk_used_|float > 70 }}'
        friendly_name: 'Critical Disk Use'

alert:
  disk_use_critical:
    name: Rpi Disk Use Is Critical
    entity_id: binary_sensor.critical_disk_use
    repeat: 60
    skip_first: False
    notifiers:
      - pushbullet_isa

automation:
  - alias: 'Hass Started'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      # Event can also be 'shutdown'
      event: start
    action:
      - service: notify.pushbullet_isa
        data:
          title: 'Rpi Hass Online'
          message: 'Online'

  - alias: 'Hass Stopped'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      # Event can also be 'shutdown'
      event: shutdown
    action:
      - service: notify.pushbullet_isa
        data:
          title: 'Rpi Hass Offline'
          message: 'Offline'
